version: '3.5'

services:
  web:
    depends_on:
      - db
    image: 'vmeste:latest'
    ports:
      - '4000:4000'
    env_file:
      - docker.env
  db:
    image: postgres:10-alpine
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    env_file:
      - docker.env
